//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFXTransaction
    {
        public long idTransaction { get; set; }
        public string type { get; set; }
        public decimal amount { get; set; }
        public string fitID { get; set; }
        public string name { get; set; }
        public string memo { get; set; }
        public string checkNum { get; set; }
        public string uniqueId { get; set; }
        public string bankId { get; set; }
        public string accountId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
